const LOCATION_API = import.meta.env.VITE_LOCATION_API;
const BACKEND_API = import.meta.env.VITE_BACKEND_API;
const BACKEND_WS = import.meta.env.VITE_BACKEND_WS;
const MIDTRANS_CLIENT_KEY = import.meta.env.VITE_MIDTRANS_CLIENT_KEY;
const MIDTRANS_SNAP_URL = import.meta.env.VITE_MIDTRANS_SNAP_URL;

export { LOCATION_API, BACKEND_API, BACKEND_WS, MIDTRANS_CLIENT_KEY, MIDTRANS_SNAP_URL };